// client-nuxt/app/pages/signup/guide.vue
<script setup lang="ts">
import { Form } from '@/components/form'
import type { FieldConfig } from '@/components/form'

// Define form fields
const fields: FieldConfig[] = [
  {
    name: 'name',
    label: 'Full Name',
    type: 'text',
    required: true,
    placeholder: 'Enter your full name',
    helperText: 'Please enter your full name as it appears on official documents',
    validation: {
      min: 2,
      max: 100,
      message: 'Name must be between 2 and 100 characters'
    }
  },
  {
    name: 'email',
    label: 'Email Address',
    type: 'text',
    inputType: 'email',
    required: true,
    placeholder: 'Enter your email address',
    helperText: 'We will send a verification link to this email',
    validation: {
      pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
      message: 'Please enter a valid email address'
    }
  },
  {
    name: 'country',
    label: 'Country',
    type: 'select',
    required: true,
    placeholder: 'Select your country',
    options: [
      { value: 'us', label: 'United States' },
      { value: 'ca', label: 'Canada' },
      { value: 'uk', label: 'United Kingdom' },
      { value: 'au', label: 'Australia' },
      { value: 'other', label: 'Other' }
    ]
  },
  {
    name: 'interests',
    label: 'Interests',
    type: 'checkbox',
    required: true,
    options: [
      { value: 'sports', label: 'Sports' },
      { value: 'music', label: 'Music' },
      { value: 'art', label: 'Art' },
      { value: 'travel', label: 'Travel' },
      { value: 'technology', label: 'Technology' }
    ],
    helperText: 'Select at least one interest',
    validation: {
      min: 1,
      message: 'Please select at least one interest'
    }
  },
  {
    name: 'bio',
    label: 'Bio',
    type: 'textarea',
    placeholder: 'Tell us about yourself',
    helperText: 'Optional: Share something about yourself with the community',
    validation: {
      max: 500,
      message: 'Bio must be less than 500 characters'
    }
  }
]

// Handle form submission
const handleSubmit = (data: Record<string, any>) => {
  console.log('Form submitted:', data)
  // Handle form submission here
}

</script>

<template>
    <div class="container mx-auto py-10">
        <h1 class="text-3xl font-bold mb-8 text-center">Signup Guide</h1>
        
        <Form 
          :fields="fields" 
          submitButtonText="Continue" 
          title="Create Your Account"
          description="Please fill out the form below to get started with your account."
          @submit="handleSubmit"
        />
    </div>
</template>

// client/src/app/(auth)/signup/guide/page.tsx
"use client"
import Form from "@/components/form";

const categories = [
  { value: "technology", label: "Technology" },
  { value: "design", label: "Design" },
  { value: "marketing", label: "Marketing" },
  { value: "business", label: "Business" },
  { value: "education", label: "Education" },
  { value: "health", label: "Health" },
  { value: "finance", label: "Finance" },
  { value: "entertainment", label: "Entertainment" },
]

const languages = [
  { value: "english", label: "English" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
  { value: "russian", label: "Russian" },
  { value: "arabic", label: "Arabic" },
]



type GuideForm = {
    bio: string
    categories: string[]
    languages: string[]
    name: string
}


export default function SignupGuide() {
  const handleSubmit = (data: GuideForm) => {
    console.log("Form submitted:", data)
    // Handle form submission here
  }

  return (
    <Form
      title="Profile Information"
      description="Complete your profile information below"
      fields={[
        {
          type: "text",
          name: "name",
          label: "Guide Name",
          placeholder: "Enter guide name",
          required: true,
          validation: {
            min: 2,
            max: 100,
          },
          helperText: "Your full name as it appears on your ID.",
        },
        {
          type: "textarea",
          name: "bio",
          label: "Bio",
          placeholder: "Tell us about yourself...",
          required: true,
          validation: {
            min: 10,
            max: 500,
          },
          helperText: "Write a short bio to introduce yourself to others.",
        },
        {
          type: "dropdown-checkbox",
          name: "categories",
          label: "Categories",
          options: categories,
          placeholder: "Select categories",
          required: true,
          validation: {
            min: 1,
          },
          helperText: "Select the categories that interest you.",
        },
        {
          type: "dropdown-checkbox",
          name: "languages",
          label: "Languages",
          options: languages,
          placeholder: "Select languages",
          required: true,
          validation: {
            min: 1,
          },
          helperText: "Select the languages you speak.",
        },
      ]}
      onSubmit={handleSubmit}
      submitButtonText="Save Profile"
    />
  )
}
