// client-nuxt/app/components/form/FormFieldBase.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { Label } from '@/components/ui/label'

const props = defineProps<{
  name: string
  label: string
  helperText?: string
  required?: boolean
  class?: HTMLAttributes['class']
  error?: string
}>()
</script>

<template>
  <div :class="`space-y-2 ${props.class || ''}`">
    <Label :for="name" class="flex items-center gap-1">
      {{ label }}
      <span v-if="required" class="text-red-500">*</span>
    </Label>
    
    <slot />

    <p v-if="error" class="text-sm text-red-500 ml-3">{{ error }}</p>
    <p v-else-if="helperText" class="text-sm text-muted-foreground">{{ helperText }}</p>
  </div>
</template>

// client/src/components/form/FormFieldBase.tsx
"use client"

import type * as React from "react"
import { Label } from "@/components/ui/label"
import type { FieldErrors } from "react-hook-form"

export type FormFieldBaseProps = {
  name: string
  label: string
  helperText?: string
  errors: FieldErrors
  required?: boolean
  className?: string
  children: React.ReactNode
}

export function FormFieldBase({
  name,
  label,
  helperText,
  errors,
  required = false,
  className = "",
  children,
}: FormFieldBaseProps) {
  return (
    <div className={`space-y-2 ${className}`}>
      <Label htmlFor={name} className="flex items-center gap-1">
        {label}
        {required && <span className="text-red-500">*</span>}
      </Label>
      
      {children}

      {errors[name] && <p className="text-sm text-red-500">{errors[name]?.message as string}</p>}
      {!errors[name]  && helperText && <p className="text-sm text-muted-foreground">{helperText}</p>}
    </div>
  )
}
