// client/src/components/form/index.tsx
"use client"

import { useEffect, useMemo } from  "react"
import { Button } from "@/components/ui/button"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import { Input } from "../ui/input"
import { FormFieldBase } from "./FormFieldBase"
import { Textarea } from "../ui/textarea"
import { CheckboxDropdown } from "../CheckboxDropdown"
import SelectDropdown from "../SelectDropdown"
import { CheckboxFieldConfig, FieldConfig, TextFieldConfig, SelectFieldConfig } from "./types"
import { validateCheckbox, validateText, validateSelect } from "./validations"
import { CategorizedCheckboxDropdown } from "../CategorizedCheckboxDropdown"


type FormProps<T> = {
  fields: FieldConfig[]
  onSubmit: (data: T) => void
  onChange?: (data: Partial<T>) => void
  submitButtonText?: string
  title?: string
  description?: string
} & (
  | { 
      onCancel?: undefined; 
      cancelButtonText?: undefined 
    } // Neither exists
  | { 
    onCancel: () => void; 
    cancelButtonText: string 
  } // Both required
)

export default function Form<T>({
  fields,
  onSubmit,
  onChange,
  submitButtonText = "Submit",
  title,
  description
}: FormProps<T>) {
  // Generate Zod schema dynamically based on field configurations
  const generateZodSchema = () => {
    const schemaMap: Record<string, z.ZodTypeAny> = {}; // ✅ Correct type

    fields.forEach(field => {
      let fieldSchema: z.ZodString | z.ZodArray<z.ZodString> = z.string();
      
      if (field.type === 'textarea' || field.type === 'text') 
        fieldSchema = validateText(field as TextFieldConfig)
      if (field.type === 'checkbox' || field.type === 'categorized-checkbox') 
        fieldSchema = validateCheckbox(field as CheckboxFieldConfig)
      if (field.type === 'select') 
        fieldSchema = validateSelect(field as SelectFieldConfig)
      
      schemaMap[field.name] = fieldSchema
    })

    return z.object(schemaMap)
  }

  const schema = generateZodSchema()
  type FormValues = z.infer<typeof schema>

  // Setup form
  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors }
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: fields.reduce((acc, field) => {
      acc[field.name] = field.type === 'checkbox' ? [] : ''
      return acc
    }, {} as Record<string, unknown> )
  })

  // Set up subscription to form changes instead of watching all values
  useEffect(() => {
    if (!onChange) return;
    
    // Subscribe to form changes
    const subscription = watch((formValues) => {
      onChange(formValues as Partial<T>);
    });
    
    // Cleanup subscription
    return () => subscription.unsubscribe();
  }, [watch, onChange]);
  
  // Handle form submission
  const onSubmitHandler = (data: FormValues) => {
    onSubmit(data as T)
  }

  // Render field based on type
  const renderField = (field: FieldConfig) => {
    switch (field.type) {
      case 'text':
        return (
            <FormFieldBase
              key={field.name}
              name={field.name}
              label={field.label}
              helperText={field.helperText}
              errors={errors}
              required={field.required}>
              <Input 
                id={field.name} type={field.inputType || 'text'} 
                placeholder={field.placeholder} 
                disabled={field.disabled} 
                {...register(field.name)} />
            </FormFieldBase>
          
        )

      case 'textarea':
        return (
          <FormFieldBase
            key={field.name}
            name={field.name}
            label={field.label}
            helperText={field.helperText}
            errors={errors}
            required={field.required}>
            <Textarea
              id={field.name}
              className={`min-h-[${6 * 24}px]`}
              placeholder={field.placeholder}
              disabled={field.disabled}
              {...register(field.name)} 
            />
          </FormFieldBase>
        )

      case 'checkbox':
        return (
          <FormFieldBase
            key={field.name}
            name={field.name}
            label={field.label}
            helperText={field.helperText}
            errors={errors}
            required={field.required}>
              <CheckboxDropdown
                key={field.name}
                name={field.name}
                label={field.label}
                options={field.options}
                placeholder={field.placeholder}
                helperText={field.helperText}
                register={register}
                watch={watch}
                required={field.required}
                setValue={setValue}
                disabled={field.disabled}/>

          </FormFieldBase>
        )
      case 'categorized-checkbox':
        return (
          <FormFieldBase
            key={field.name}
            name={field.name}
            label={field.label}
            helperText={field.helperText}
            errors={errors}
            required={field.required}>
              <CategorizedCheckboxDropdown
                key={field.name}
                name={field.name}
                label={field.label}
                options={field.options}
                placeholder={field.placeholder}
                register={register}
                watch={watch}
                required={field.required}
                setValue={setValue}
                disabled={field.disabled}/>

          </FormFieldBase>
        )
      case 'select':
        return (
          <FormFieldBase
            key={field.name}
            name={field.name}
            label={field.label}
            helperText={field.helperText}
            errors={errors}
            required={field.required}>
              <SelectDropdown
                key={field.name}
                name={field.name}
                label={field.label}
                options={field.options}
                placeholder={field.placeholder}
                helperText={field.helperText}
                register={register}
                watch={watch}
                setValue={setValue}
                disabled={field.disabled}/>
          </FormFieldBase>
        )

      default:
        return null
    }
  }

  return (
    <form onSubmit={handleSubmit(onSubmitHandler)} className="w-full max-w-2xl mx-auto space-y-6 px-6 bg-white  max-h-min  py-10">
      {(title || description) && (
        <div className="space-y-2">
          {title && <h2 className="text-2xl font-bold">{title}</h2>}
          {description && <p className="text-muted-foreground">{description}</p>}
        </div>
      )}

      {fields.map(renderField)}

      <Button type="submit" className="w-full">
        {submitButtonText}
      </Button>
    </form>
  )
}

// client-nuxt/app/components/form/Form.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import FormFieldBase from './FormFieldBase.vue'
import SelectDropdown from '../SelectDropdown.vue'
import CheckboxDropdown from '../CheckboxDropdown.vue'
import type { FieldConfig, TextFieldConfig, TextareaFieldConfig, CheckboxFieldConfig, SelectFieldConfig } from './types'
import { useForm } from 'vee-validate'
import { createFormSchema } from './validations'
import { toTypedSchema } from '@vee-validate/zod'
import { ref } from 'vue'

const props = defineProps<{
  fields: FieldConfig[]
  submitButtonText?: string
  title?: string
  description?: string
}>()

const emit = defineEmits<{
  (e: 'submit', data: Record<string, any>): void
  (e: 'change', data: Record<string, any>): void
}>()

// Track which fields have been blurred
const blurredFields = ref<Record<string, boolean>>({})

// Initialize blurred fields
props.fields.forEach(field => {
  blurredFields.value[field.name] = false
})

// Create the validation schema
const validationSchema = toTypedSchema(createFormSchema(props.fields))

// Initialize form with vee-validate
const { handleSubmit, errors, values, setFieldValue } = useForm({
  validationSchema,
  initialValues: props.fields.reduce((acc, field) => {
    acc[field.name] = field.type === 'checkbox' ? [] : ''
    return acc
  }, {} as Record<string, any>),
  validateOnMount: false,
  validateOnBlur: true,
  validateOnChange: false
})

// Handle form submission
const onSubmit = handleSubmit((values) => {
  // Mark all fields as blurred on submit
  props.fields.forEach(field => {
    blurredFields.value[field.name] = true
  })
  emit('submit', values)
})

// Handle input change
const handleChange = (field: string, value: string | string[] | number) => {
  setFieldValue(field, value)
  emit('change', values)
}

// Handle field blur
const handleBlur = (fieldName: string) => {
  blurredFields.value[fieldName] = true
}

// Helper to check if field should show error
const shouldShowError = (fieldName: string) => {
  return blurredFields.value[fieldName]
}
</script>

<template>
  <form @submit="onSubmit" class="w-full max-w-2xl mx-auto space-y-6 p-4">
    <div v-if="title || description" class="space-y-2">
      <h2 v-if="title" class="text-2xl font-bold">{{ title }}</h2>
      <p v-if="description" class="text-muted-foreground">{{ description }}</p>
    </div>

    <template v-for="field in fields" :key="field.name">
      <!-- Text Field -->
      <FormFieldBase 
        v-if="field.type === 'text'"
        :name="field.name"
        :label="field.label"
        :helperText="field.helperText"
        :error="shouldShowError(field.name) ? errors[field.name] : undefined"
        :required="field.required"
      >
        <Input 
          :id="field.name"
          :type="(field as TextFieldConfig).inputType || 'text'"
          :placeholder="field.placeholder"
          :disabled="field.disabled"
          v-model="values[field.name]"
          @update:modelValue="(value: string | number) => handleChange(field.name, value)"
          @blur="handleBlur(field.name)"
        />
      </FormFieldBase>

      <!-- Textarea Field -->
      <FormFieldBase 
        v-else-if="field.type === 'textarea'"
        :name="field.name"
        :label="field.label"
        :helperText="field.helperText"
        :error="shouldShowError(field.name) ? errors[field.name] : undefined"
        :required="field.required"
      >
        <Textarea
          :id="field.name"
          :placeholder="field.placeholder"
          :disabled="field.disabled"
          v-model="values[field.name]"
          @update:modelValue="(value: string | number) => handleChange(field.name, value)"
          @blur="handleBlur(field.name)"
        />
      </FormFieldBase>

      <!-- Select Field -->
      <FormFieldBase 
        v-else-if="field.type === 'select'"
        :name="field.name"
        :label="field.label"
        :helperText="field.helperText"
        :error="shouldShowError(field.name) ? errors[field.name] : undefined"
        :required="field.required"
      >
        <SelectDropdown 
          :options="(field as SelectFieldConfig).options"
          :placeholder="field.placeholder"
          v-model="values[field.name]"
          :disabled="field.disabled"
          @update:modelValue="(value: string) => handleChange(field.name, value)"
          @blur="handleBlur(field.name)"
        />
      </FormFieldBase>

      <!-- Checkbox Field -->
      <FormFieldBase 
        v-else-if="field.type === 'checkbox'"
        :name="field.name"
        :label="field.label"
        :helperText="field.helperText"
        :error="shouldShowError(field.name) ? errors[field.name] : undefined"
        :required="field.required"
      >
        <CheckboxDropdown
          :options="(field as CheckboxFieldConfig).options"
          :label="field.label"
          :placeholder="field.placeholder"
          v-model="values[field.name]"
          :disabled="field.disabled"
          @update:modelValue="(value: string[]) => handleChange(field.name, value)"
          @blur="handleBlur(field.name)"
        />
      </FormFieldBase>
    </template>

    <Button type="submit" class="w-full">
      {{ submitButtonText || 'Submit' }}
    </Button>
  </form>
</template>
